; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html

[env:swervolf_nexys]
platform = chipsalliance
board = swervolf_nexys
framework = wd-riscv-sdk

monitor_speed = 115200

#debug_tool = whisper

board_build.bitstream_file = RVfpga/src/rvfpganexys.bit

#board_debug.verilator.binary = D:\Ingenieria_Electrica_UCR\2024\Segundo_Semestre_2024\Lab_de_digitales\Repositorio\RVfpga-g1\RVfpga\verilatorSIM\Vrvfpgasim.exe
#build_flags = -DTRACE_FILE="D:\Ingenieria_Electrica_UCR\2024\Segundo_Semestre_2024\Lab_de_digitales\Repositorio\RVfpga-g1\RVfpga\trace.vcd"

board_debug.verilator.binary = /home/sixto/RVfpga-g1/RVfpga/verilatorSIM/Vrvfpgasim

